### ISSUE TITLE
Change default behaviour of headerCommand

### ISSUE THREAD

**Issue by DonHuskini** [nubasedev/react-mde#337]
@andrerpena I'd like to know if it's possible to add "##" on the markdown editor instead of "###" which seems to be the default behavior when I call the command headerCommand on v.12.*

**Comment by andrerpena** [comment]
Hello kindred brazilian. 
v12 is still far from done, but I just relased this commit https://github.com/andrerpena/react-mde/commit/cae3ee20c35d213118808f0e1779c8852d8fc28d on version 12.0.8@next that actually exports all heading command levels individually. In order to have `##`, just use the `headingLevel2Command`.

This file uses the `headingLevel1Command` but just replace it with `headingLevel2Command`. https://github.com/andrerpena/react-mde/blob/master/demo/index.tsx

**Comment by gabrielmlinassi** [comment]
@andrerpena That's exactly what I needed. Thanks! 
BTW, I really enjoyed your decision to make react-mde headless. Looking forward to the new releases.
